name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]
jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
          - run: realpath .
          - run: ls -l
          - name: Check out repository code
            uses: actions/checkout@v4
          - run: realpath .
          - run: ls -l
